# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  schedule:
  - cron: "0 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1.4.2

    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build a new version
      id: build
      run: yarn build
    
    - name: Commit changes
      if: ${{ steps.build.outputs.needs_publish }}
      run: |
        git config --local user.name GitHub Actions
        git config --local user.email actions@github.com
        git add .
        git commit --no-verify --message="release: ${{ steps.build.outputs.version_number }}"
        git tag --annotate "${{ steps.build.outputs.version_number }}" --message="v${{ steps.build.outputs.version_number }}"
      
    - name: Push changes
      if: ${{ steps.build.outputs.needs_publish }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
    
    # From: https://sergiodxa.com/articles/github-actions-npm-publish/
    - name: Publish changes
      #if: ${{ steps.build.outputs.needs_publish }}
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        npm publish
